### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/rbxplore#1]
- [ ] Flags (`rbxplore [options] [file]`)
	- [ ] `[file]`
		- Open file in a new session, associated with the file.
	- [ ] `[options]`
		- [ ] `--new`
			- If running with a GUI, force a new session to be opened.
		- [ ] `--settings [file]`
			- Read and write settings from a given settings file.
		- [ ] `--rmd [file]`
			- Read and write ReflectionMetadata from a given file.
			- If unspecified, `ReflectionMetadata.xml` is read from same location as the executable, if it exists.
		- [ ] `--api [file]`
			- Read and write API dump from a given file.
			- If unspecified, `API.txt` is read from same location as the executable, if it exists.
		- [ ] `--updatedata [url]`
			- Update ReflectionMetadata and API dump files from a URL.
			- URL is optional, if unspecified, a default location will be used.
		- [ ] `--shell`
			- Run as shell; do not create GUI.
			- Useful for quick conversion of files.
		- [ ] `--output [file]`
			- If running as shell, export the input file to the given file.
		- [ ] `--format [format]`
			- If running as shell, export the input file in the given format.
			- `rbxl`, `rbxlx`, `rbxm`, `rbxmx`, `json`
			- Append `_min` for minimized format.
		- [ ] `--debug`
			- Output debug info to stdout.
- [ ] File selector context
- [ ] Export context
	- File location (enters Select context)
	- Format dropdown selector
	- Readable option
		- For formats that apply, content is either minimized or made readable.
- [ ] Prompt dialog context
- [ ] Settings context
	- [ ] Theme selector.
	- [ ] GUI scale selector.
	- [ ] Text Editor.
		- Font.
		- Tab Width.
	- [ ] Data Updater.
		- Analogous to --updatedata flag
- [ ] Editor context
	- Actions
		- [ ] (New, Open) If a session is already open, spawn a new process.
		- [ ] (Close) If session is unsaved when closing, prompt for save.
	- [ ] Tabbed layout.
	- [ ] Adding/Removing tree nodes.
	- [ ] Dragging tree nodes.
	- [ ] Double clicking certain nodes opens a tab with a text editor.
		- Script.Source
		- StringValue.Value
	- [ ] Set "unsaved" state when data changes.
	- [ ] Property editor
		- Display type in tool tip
		- Types
			- string, ProtectedString
				- [ ] Simple text box.
				- [ ] Alternative: inline multiline text box.
				- [ ] Alternative: open text editor in tab.
